/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppThoughtsRouteImport } from './routes/app.thoughts'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReelsRouteImport } from './routes/app.reels'
import { Route as AppPregnancyRouteImport } from './routes/app.pregnancy'
import { Route as AppMusicRouteImport } from './routes/app.music'
import { Route as AppMealsRouteImport } from './routes/app.meals'
import { Route as AppExerciseRouteImport } from './routes/app.exercise'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppDanceRouteImport } from './routes/app.dance'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AppPregnancyIndexRouteImport } from './routes/app.pregnancy.index'
import { Route as AppPregnancyOnboardingRouteImport } from './routes/app.pregnancy.onboarding'
import { Route as AppPregnancyMealsRouteImport } from './routes/app.pregnancy.meals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppThoughtsRoute = AppThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppPregnancyRoute = AppPregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicRoute = AppMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciseRoute = AppExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDanceRoute = AppDanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPregnancyIndexRoute = AppPregnancyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPregnancyRoute,
} as any)
const AppPregnancyOnboardingRoute = AppPregnancyOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppPregnancyRoute,
} as any)
const AppPregnancyMealsRoute = AppPregnancyMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppPregnancyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dance': typeof AppDanceRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/exercise': typeof AppExerciseRoute
  '/app/meals': typeof AppMealsRoute
  '/app/music': typeof AppMusicRoute
  '/app/pregnancy': typeof AppPregnancyRouteWithChildren
  '/app/reels': typeof AppReelsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thoughts': typeof AppThoughtsRoute
  '/app/': typeof AppIndexRoute
  '/app/pregnancy/meals': typeof AppPregnancyMealsRoute
  '/app/pregnancy/onboarding': typeof AppPregnancyOnboardingRoute
  '/app/pregnancy/': typeof AppPregnancyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dance': typeof AppDanceRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/exercise': typeof AppExerciseRoute
  '/app/meals': typeof AppMealsRoute
  '/app/music': typeof AppMusicRoute
  '/app/reels': typeof AppReelsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thoughts': typeof AppThoughtsRoute
  '/app': typeof AppIndexRoute
  '/app/pregnancy/meals': typeof AppPregnancyMealsRoute
  '/app/pregnancy/onboarding': typeof AppPregnancyOnboardingRoute
  '/app/pregnancy': typeof AppPregnancyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dance': typeof AppDanceRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/exercise': typeof AppExerciseRoute
  '/app/meals': typeof AppMealsRoute
  '/app/music': typeof AppMusicRoute
  '/app/pregnancy': typeof AppPregnancyRouteWithChildren
  '/app/reels': typeof AppReelsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/thoughts': typeof AppThoughtsRoute
  '/app/': typeof AppIndexRoute
  '/app/pregnancy/meals': typeof AppPregnancyMealsRoute
  '/app/pregnancy/onboarding': typeof AppPregnancyOnboardingRoute
  '/app/pregnancy/': typeof AppPregnancyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/api/chat'
    | '/app/calendar'
    | '/app/dance'
    | '/app/emergency'
    | '/app/exercise'
    | '/app/meals'
    | '/app/music'
    | '/app/pregnancy'
    | '/app/reels'
    | '/app/settings'
    | '/app/thoughts'
    | '/app/'
    | '/app/pregnancy/meals'
    | '/app/pregnancy/onboarding'
    | '/app/pregnancy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/api/chat'
    | '/app/calendar'
    | '/app/dance'
    | '/app/emergency'
    | '/app/exercise'
    | '/app/meals'
    | '/app/music'
    | '/app/reels'
    | '/app/settings'
    | '/app/thoughts'
    | '/app'
    | '/app/pregnancy/meals'
    | '/app/pregnancy/onboarding'
    | '/app/pregnancy'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/api/chat'
    | '/app/calendar'
    | '/app/dance'
    | '/app/emergency'
    | '/app/exercise'
    | '/app/meals'
    | '/app/music'
    | '/app/pregnancy'
    | '/app/reels'
    | '/app/settings'
    | '/app/thoughts'
    | '/app/'
    | '/app/pregnancy/meals'
    | '/app/pregnancy/onboarding'
    | '/app/pregnancy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/thoughts': {
      id: '/app/thoughts'
      path: '/thoughts'
      fullPath: '/app/thoughts'
      preLoaderRoute: typeof AppThoughtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reels': {
      id: '/app/reels'
      path: '/reels'
      fullPath: '/app/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pregnancy': {
      id: '/app/pregnancy'
      path: '/pregnancy'
      fullPath: '/app/pregnancy'
      preLoaderRoute: typeof AppPregnancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/music': {
      id: '/app/music'
      path: '/music'
      fullPath: '/app/music'
      preLoaderRoute: typeof AppMusicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meals': {
      id: '/app/meals'
      path: '/meals'
      fullPath: '/app/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercise': {
      id: '/app/exercise'
      path: '/exercise'
      fullPath: '/app/exercise'
      preLoaderRoute: typeof AppExerciseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dance': {
      id: '/app/dance'
      path: '/dance'
      fullPath: '/app/dance'
      preLoaderRoute: typeof AppDanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pregnancy/': {
      id: '/app/pregnancy/'
      path: '/'
      fullPath: '/app/pregnancy/'
      preLoaderRoute: typeof AppPregnancyIndexRouteImport
      parentRoute: typeof AppPregnancyRoute
    }
    '/app/pregnancy/onboarding': {
      id: '/app/pregnancy/onboarding'
      path: '/onboarding'
      fullPath: '/app/pregnancy/onboarding'
      preLoaderRoute: typeof AppPregnancyOnboardingRouteImport
      parentRoute: typeof AppPregnancyRoute
    }
    '/app/pregnancy/meals': {
      id: '/app/pregnancy/meals'
      path: '/meals'
      fullPath: '/app/pregnancy/meals'
      preLoaderRoute: typeof AppPregnancyMealsRouteImport
      parentRoute: typeof AppPregnancyRoute
    }
  }
}

interface AppPregnancyRouteChildren {
  AppPregnancyMealsRoute: typeof AppPregnancyMealsRoute
  AppPregnancyOnboardingRoute: typeof AppPregnancyOnboardingRoute
  AppPregnancyIndexRoute: typeof AppPregnancyIndexRoute
}

const AppPregnancyRouteChildren: AppPregnancyRouteChildren = {
  AppPregnancyMealsRoute: AppPregnancyMealsRoute,
  AppPregnancyOnboardingRoute: AppPregnancyOnboardingRoute,
  AppPregnancyIndexRoute: AppPregnancyIndexRoute,
}

const AppPregnancyRouteWithChildren = AppPregnancyRoute._addFileChildren(
  AppPregnancyRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDanceRoute: typeof AppDanceRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppExerciseRoute: typeof AppExerciseRoute
  AppMealsRoute: typeof AppMealsRoute
  AppMusicRoute: typeof AppMusicRoute
  AppPregnancyRoute: typeof AppPregnancyRouteWithChildren
  AppReelsRoute: typeof AppReelsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThoughtsRoute: typeof AppThoughtsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDanceRoute: AppDanceRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppExerciseRoute: AppExerciseRoute,
  AppMealsRoute: AppMealsRoute,
  AppMusicRoute: AppMusicRoute,
  AppPregnancyRoute: AppPregnancyRouteWithChildren,
  AppReelsRoute: AppReelsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThoughtsRoute: AppThoughtsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
